### ISSUE TITLE
can't find testing syntax such as describe

### ISSUE THREAD

**Issue by ellerylee369** [SierraNL/webpack-typescript-jasmine#1]
Hi,

 I downloaded your jasmine/karma/webpack/typescript repo because I was looking for a way to test non Angular typescript with Jasmine.  I did an npm install in the directory where package.json is.  When i then tried "node dev build" in command line, I got an error where it could not find testing syntax such as "describe etc."  When i then tried "npm run test", I get the error that no test is specified. Did I miss a step in running this properly?  Your help would be greatly appreciated.  Thank you.

![Annotation 2020-05-24 221923](https://user-images.githubusercontent.com/49534643/82780923-69804980-9e0d-11ea-8e8d-59fffdbffac4.jpg)

**Comment by SierraNL** [comment]
I'll try and see if I can update the example, the world has changed since I made this, I guess.

**Comment by SierraNL** [comment]
Just updated the example, it used to have typings, but that's in npm nowadays.
Updated all the packages and fixed some minor things.

Could you give it a try now?
Just pull the repo and `npm install` and `npm test`

**Comment by ellerylee369** [comment]
Thanks so much for updating the example and fixing some minor things.  It works perfectly now.
